### ISSUE TITLE
Release a Wagtail-1.4.1-compatible version on PyPI

### ISSUE THREAD

**Issue by akhayyat** [infoportugal/wagtail-modeltranslation#72]
The current release on PyPI, 0.4.4 is incompatible with the recently released Wagtail version 1.4.1:

```pytb
from wagtail_modeltranslation.models import TranslationMixin
  File "<python>/site-packages/wagtail_modeltranslation/models.py", line 16, in <module>
    from wagtail.wagtailadmin.views.pages import get_page_edit_handler,\
ImportError: cannot import name 'get_page_edit_handler'
```

**Comment by nikonikoniko** [comment]
Which version of wagtail is currently compatible with wagtail-modeltranslation?

**Comment by akhayyat** [comment]
It works well with wagtail 1.3.1.

**Comment by Alexandre27** [comment]
Version 0.5.0a is compatible with Wagtail 1.4.x
