### ISSUE TITLE
Problems migrating existing models to new modeltranslation installation

### ISSUE THREAD

**Issue by SalahAdDin** [infoportugal/wagtail-modeltranslation#22]
Hi guys, i was working with wagtail 8.0 and i have many page in my db.
I migrating all models to 1.0 and modeltranslation and i have this issue:
![no titulos](https://cloud.githubusercontent.com/assets/5034215/9228519/7386f6f4-40de-11e5-9a53-dfb076da9214.png)

Where are titles?

Now i have a problem, in all pages that i try to edit or create i get screen of this type:
![problemas translation](https://cloud.githubusercontent.com/assets/5034215/9232115/72305cce-40f1-11e5-9fea-40214dab19e1.png)

What is the problem? i need help urgently!

**Comment by SalahAdDin** [comment]
Here is the traceback:
```bash

AttributeError at /

type object 'HomePage' has no attribute 'panels'

Request Method: 	GET
Request URL: 	http://localhost:8000/
Django Version: 	1.8.3
Exception Type: 	AttributeError
Exception Value: 	

type object 'HomePage' has no attribute 'panels'

Exception Location: 	/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/wagtail_modeltranslation/models.py in _patch_inlinepanel, line 353
Python Executable: 	/media/tulipan/Datos/Proyectos/Trabajo/CCCT/bin/python
Python Version: 	3.4.3
Python Path: 	

['/media/tulipan/Datos/Proyectos/Trabajo/CCCT/ccct',
 '/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4',
 '/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/plat-x86_64-linux-gnu',
 '/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages']

Server time: 	Mié, 12 Ago 2015 21:13:10 -0500
Traceback Switch to copy-and-paste view

    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/core/handlers/base.py in get_response

                                        response = wrapped_callback(request, *callback_args, **callback_kwargs)

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/wagtail/wagtailcore/views.py in serve

                        page, args, kwargs = request.site.root_page.specific.route(request, path_components)

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/utils/functional.py in __get__

                            res = instance.__dict__[self.name] = self.func(instance)

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/wagtail/wagtailcore/models.py in specific

                                return content_type.get_object_for_this_type(id=self.id)

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/contrib/contenttypes/models.py in get_object_for_this_type

                            return self.model_class()._base_manager.using(self._state.db).get(**kwargs)

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/models/query.py in get

                            num = len(clone)

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/models/query.py in __len__

                            self._fetch_all()

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/models/query.py in _fetch_all

                                self._result_cache = list(self.iterator())

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/models/query.py in iterator

                                obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/django/db/models/base.py in from_db

                                new = cls(*values)

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/wagtail_modeltranslation/translator.py in new_init

                            old_init(self, *args, **kwargs)

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/wagtail_modeltranslation/models.py in __init__

                                    trtab = TranslationMixin._patch_panel(self, panel)

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/wagtail_modeltranslation/models.py in _patch_panel

                                TranslationMixin._patch_inlinepanel(instance, panel)

         ...
    ▶ Local vars
    /media/tulipan/Datos/Proyectos/Trabajo/CCCT/lib/python3.4/site-packages/wagtail_modeltranslation/models.py in _patch_inlinepanel

                return FieldRowPanel(

                    patched_fields,

                    classname=frpanel.classname)

            @classmethod

            def _patch_inlinepanel(cls, instance, panel):

                inline_panels = getattr(

                                instance.__class__, panel.relation_name).related.model.panels

         ...

                try:

                    inline_model_tr_fields = translator.get_options_for_model(

                        getattr(

                            instance.__class__, panel.relation_name).related.model).fields

                except NotRegistered:

                    return None

    ▼ Local vars
    Variable 	Value
    instance 	

    <HomePage: >

    cls 	

    <class 'wagtail_modeltranslation.models.TranslationMixin'>

    panel 	

    <wagtail.wagtailadmin.edit_handlers.InlinePanel object at 0x7fa6e2a43860>
```

**Comment by anbz** [comment]
Same issue here with wagtail-modeltranslation 0.2.2 and Wagtail 1.0 as aslo described in  #10 .

**Comment by rmartins90** [comment]
I'll check and fix this later today.

**Comment by SalahAdDin** [comment]
Oh man, thank you, i need this very urgently, and i want help you for the tabbed interface feature :D

**Comment by anbz** [comment]
@rmartins90 Any updates on this issue, please?

**Comment by SalahAdDin** [comment]
Yes, please, please.

**Comment by SalahAdDin** [comment]
See: delete all text and put all as blanc fields:
![borratodo](https://cloud.githubusercontent.com/assets/5034215/9284548/548e8d46-42a2-11e5-81d7-44a6207903bc.png)

**Comment by SalahAdDin** [comment]
Why it creates three language fields and don't delete the default field?

**Comment by SalahAdDin** [comment]
@tomdyson can you help us here?

**Comment by SalahAdDin** [comment]
Ok, more problems

I think that you can think about change your migration method, it's very crazy:

Create all translate fields with each languages in your settings, but, this is a very big problem; left a untranslated field that contains the initial existing data, but this data doesn't work with the translation app, i mean, the app takes the default language fields for show but any translation field have information, the information exist in unstranslated field, this cause that the slug doesn't works, the page doesn't show anything, anything, but, in the admin the translation field for your default language takes the information from unstranslated field and show it in a page's preview fine.

I think that this problem could be caused because, in my case, i have a language-code different of my language in languages settings:
```python
LANGUAGE_CODE = 'es-co'  # Por defecto'en-us'
LANGUAGES = (
    ('es',  _('Spanish')),
    ('en',  _('English')),
    ('tr',  _('Turkish')),
)
```
This app takes 'es-co' as different of 'es', but this app should takes the language base and not an especific location.

You can see this in this pics:
![mas pruebas translation](https://cloud.githubusercontent.com/assets/5034215/9297295/ced389c8-4462-11e5-8767-8ed298750715.png)
![mas pruebas translation 2](https://cloud.githubusercontent.com/assets/5034215/9297296/cffefd64-4462-11e5-92cd-e6ca0112f23f.png)

You can see, the slug is one of firts fields, and in the final fields you can see the translated fields.

**Comment by benebun** [comment]
Just wanted to point out that there is a new ticket #30 with the same/similar issue (regression?) as here and in #10 and a possible workaround in pull request #31.

@SalahAdDin: I'm not the maintainer of this project so I hope you or anybody else don't take this the wrong way but it is impossible to help you in one issue if you combine different unrelated problems/questsions and it gets less useful/confusing for everybody else. Your problems/questions  would probably also better be addressed in the Wagtail support forum if it is not an actual issue: https://groups.google.com/forum/#!forum/wagtail

**Comment by SalahAdDin** [comment]
But, all problem have to see with modeltranslation, not with wagtail.

**Comment by SalahAdDin** [comment]
Are solved this bug already???

**Comment by Zowie** [comment]
+1 here, can work without InlinePanel though :) But it'd be great if this can be fixed

**Comment by SalahAdDin** [comment]
:+1:

**Comment by rmartins90** [comment]
Solved with v0.3. Please read the upgrade steps.

**Comment by Zowie** [comment]
Awesome thanks! Will check it out!
